# Generated by Django 2.2.4 on 2019-08-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20190813_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
